# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: CTF of Z2BNS
subtitle: ''
description: 'Because like, so love'
keywords:
author: Z2BNS
#语言
#language: en
language: zh-CN
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: http://example.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: landscape
theme: next

encrypt:
  enable: true

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:z2bns/z2bns.github.io.git

# 文章末尾添加"本文结束"标记
passage_end_tag:
  enabled: true

leancloud_counter_security:
  enable_sync: true
  app_id: KN0GiB19RNmgIeCSFonTGgzn-gzGzoHsz
  app_key: MiL8FBp9YnzlJSeHuER1p7Ua
  server_url: https://leancloud.cn
  username: vip1234pinyin@163.com
  password: zww2215552581

#添加个性化配置
live2d:
  enable: true   #开启宠物
  scriptFrom: local
  model:
    use: live2d-widget-model-hijiki
  display:
    position: right   #指定宠物显示的位置
    width: 280    #指定宠物显示的宽度
    height: 480   #指定宠物显示的高度
  mobile:
    show: false  #是否在手机上显示

#添加本地搜索
search:
  path: search.xml
  field: post
  format: html
  limit: 10000
  
  
#添加字数统计和阅读时长
symbols_count_time:
  symbols: true #文章字数统计
  time: true #文章阅读时长
  total_symbols: false #站点总字数统计
  total_time: false #站点总阅读时长
  exclude_codeblock: false #排除代码字数统计

#文章添加音乐和视频
aplayer:
  meting: true